name: CI

on:
  push:
    branches: [remove-common]
  pull_request:
    branches: [remove-common]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn tsc
      - run: yarn build
      - run: yarn test
        env:
          CI: true